from __future__ import annotations

DEFAULT_OLLAMA_BASE_URL = "http://127.0.0.1:11434"
DEFAULT_REQUEST_TIMEOUT_SECONDS = 120
DEFAULT_RAW_OUTPUT_MAX_BYTES = 8192
DEFAULT_MAX_ATTEMPTS = 2
DEFAULT_REPEATS = 3
DEFAULT_TEMPERATURE_SWEEP = [0.0, 0.2, 0.5, 0.8]
JOB_STORE_PATH = "results/job_store.sqlite"
RESULTS_LATEST_LINK = "results/latest"
